chore: testings

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -84,6 +84,10 @@ jobs:
       - run:
           name: Build docker-compose-template.yml
           command: |
+            if [ -z "$DOCKERHUB_USERNAME" ]; then
+              echo "Error: DOCKERHUB_USERNAME is not set."
+              exit 1
+            fi
             sed "s/DOCKER_IMAGE_NAME/$DOCKERHUB_USERNAME\/dagobah:latest/g" docker-compose-template.yml > docker-compose.yml
             sed -i "s/DOCKER_CONTAINER_NAME/$DOCKER_CONTAINER_NAME/g" docker-compose.yml
 
@@ -101,10 +105,15 @@ jobs:
           name: SSH into GCP instance and deploy
           command: |
             ssh -o StrictHostKeyChecking=no $GCE_SSH_USERNAME@$GCE_INSTANCE_IP \<< 'EOF'
-              docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml down
-              docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml build --pull
-              docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml up -d
-              docker image prune -f
+              # Check if docker-compose.yml exists
+              ls -l /home/$GCE_SSH_USERNAME/docker-compose.yml
+              # Use sudo for Docker commands if necessary
+              sudo docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml down
+              sudo docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml build --pull
+              sudo docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml up -d
+              sudo docker image prune -f
+              # Check if mongo-init.sh exists
+              ls -l /home/$GCE_SSH_USERNAME/db/mongo-init.sh
               sh /home/$GCE_SSH_USERNAME/db/mongo-init.sh
             EOF
 
