chore: final testings

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,3 @@
-# This config was automatically generated from your source code
-# Stacks detected: deps:java:.,tool:gradle:
 version: 2.1
 
 executors:
@@ -75,36 +73,43 @@ jobs:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASSWORD
     steps:
+      - checkout
       - run: |
           echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
           gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
           gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
 
       - run:
-          name: Build docker-compose.yml
+          name: Build docker-compose-template.yml
           command: |
-            sed -i "s/DOCKER_IMAGE_NAME/$DOCKERHUB_USERNAME\/dagobah:latest/g" docker-compose.yml
+            if [ -z "$DOCKERHUB_USERNAME" ]; then
+              echo "Error: DOCKERHUB_USERNAME is not set."
+              exit 1
+            fi
+            sed "s/DOCKER_IMAGE_NAME/$DOCKERHUB_USERNAME\/dagobah:latest/g" docker-compose-template.yml > docker-compose.yml
             sed -i "s/DOCKER_CONTAINER_NAME/$DOCKER_CONTAINER_NAME/g" docker-compose.yml
 
       - run:
-          name: SCP docker-compose.yml to GCP instance
+          name: SCP docker-compose-template.yml to GCP instance
           command: |
-            scp -i /tmp/gcp_key -o StrictHostKeyChecking=no docker-compose.yml $GCE_SSH_USERNAME@$GCE_INSTANCE_IP:/home/$GCE_SSH_USERNAME/
+            scp -o StrictHostKeyChecking=no -r ./docker-compose.yml $GCE_SSH_USERNAME@$GCE_INSTANCE_IP:/home/$GCE_SSH_USERNAME
 
       - run:
           name: SCP db folder to GCP instance
           command: |
-            scp -i /tmp/gcp_key -o StrictHostKeyChecking=no -r db $GCE_SSH_USERNAME@$GCE_INSTANCE_IP:/home/$GCE_SSH_USERNAME/db
+            scp -o StrictHostKeyChecking=no -r ./db $GCE_SSH_USERNAME@$GCE_INSTANCE_IP:/home/$GCE_SSH_USERNAME
 
       - run:
           name: SSH into GCP instance and deploy
           command: |
-            ssh -i /tmp/gcp_key -o StrictHostKeyChecking=no $GCE_SSH_USERNAME@$GCE_INSTANCE_IP" \<< 'EOF'
-              docker compose -f /home/$GCE_SSH_USERNAME"/docker-compose.yml down
-              docker compose -f /home/$GCE_SSH_USERNAME"/docker-compose.yml build --pull
-              docker compose -f /home/$GCE_SSH_USERNAME"/docker-compose.yml up -d
+            ssh -o StrictHostKeyChecking=no $GCE_SSH_USERNAME@$GCE_INSTANCE_IP \<< EOF
+              sudo usermod -aG docker $GCE_SSH_USERNAME
+              docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml down
+              docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml build --pull
+              docker compose -f /home/$GCE_SSH_USERNAME/docker-compose.yml up -d
               docker image prune -f
-              sh /home/$GCE_SSH_USERNAME/db/mongo-init.sh
+              cd /home/$GCE_SSH_USERNAME/db
+              sh ./mongo-init.sh
             EOF
 
 workflows:
